// Generated by Elysia scripts/generate_codev_contracts.py. Do not edit.
// Canonical JSON Schema SHA-256: fbd4c071b674774216cabf29ebff05fc2a5fdd2d7ec0be6d2fb2ddc3e27b0941
export const CODEV_CONTRACT = "codev-client-1" as const;
export const CODEV_SCHEMA_SHA256 = "fbd4c071b674774216cabf29ebff05fc2a5fdd2d7ec0be6d2fb2ddc3e27b0941" as const;

export type Actor = {
  local_profile_id: string;
  client_id: string;
  client_kind: "native" | "browser" | "vscode_compatibility";
  online_account_id?: string | null;
  origin?: string | null;
  surface: "local" | "marketplace" | "forge";
};

export type BrokerPolicy = {
  origin?: "http://127.0.0.1:47321";
  host?: "127.0.0.1:47321";
  port?: 47321;
  max_body_bytes?: 2097152;
  clock_skew_seconds?: 30;
};

export type BrokerProof = {
  pairing_id: string;
  browser_session_id: string;
  online_account_id: string;
  nonce: string;
  timestamp_ms: number;
  signature: string;
};

export type BrokerRequest = {
  proof: BrokerProof;
  payload_json: string;
};

export type BrokerResponse = {
  payload_json: string;
  signature: string;
};

export type BrowserApproveRequest = {
  workspace_id: string;
  revision: number;
  content_hash: string;
  grant_epoch: number;
  plan_id: string;
  plan_hash: string;
  explicitly_approved?: boolean;
};

export type BrowserCancelRequest = {
  request_id: string;
};

export type BrowserChatRequest = {
  workspace_id: string;
  revision: number;
  content_hash: string;
  grant_epoch: number;
  message: string;
  requested_gear?: string;
  request_id: string;
};

export type BrowserPatchRequest = {
  workspace_id: string;
  revision: number;
  content_hash: string;
  grant_epoch: number;
  summary: string;
  edits: {

};
};

export type BrowserPublicKey = {
  kty?: "EC";
  crv?: "P-256";
  x: string;
  y: string;
};

export type BrowserRevisionRequest = {
  workspace_id: string;
  revision: number;
  content_hash: string;
  grant_epoch: number;
};

export type BrowserWorkspaceShare = {
  workspace_id: string;
  surface: "marketplace" | "forge";
  draft_id?: string | null;
  label: string;
  base_revision: number;
  current_revision: number;
  content_hash: string;
  files: Array<WorkspaceFile>;
  scopes: Array<"read" | "propose">;
  explicitly_approved: boolean;
  expected_epoch?: number;
};

export type Capability = {
  id: string;
  available: boolean;
  requires?: Array<string>;
  reason?: string | null;
};

export type ChangePlan = {
  plan_id: string;
  workspace_id: string;
  actor: Actor;
  base_revision: number;
  workspace_hash: string;
  grant_epoch: number;
  plan_hash: string;
  summary: string;
  changes?: Array<FileChange>;
  command_id?: string | null;
  command_argv?: Array<string>;
  cwd_label: string;
  network_policy?: "none";
  expected_checks?: Array<string>;
  risks?: Array<string>;
  expires_at: string;
  recovery_note: string;
};

export type ExactApproval = {
  approval_id: string;
  actor: Actor;
  workspace_id: string;
  revision: number;
  workspace_hash: string;
  grant_epoch: number;
  operation: "patch_apply" | "command_run" | "browser_patch" | "remote_save";
  files?: Array<string>;
  plan_hash: string;
  command_argv?: Array<string>;
  cwd_label: string;
  network_policy?: "none" | "approved_remote_save";
  expires_at: string;
  one_time?: true;
  consumed?: boolean;
};

export type FileChange = {
  path: string;
  base_hash: string;
  new_text: string;
  new_hash: string;
  diff: string;
};

export type Installation = {
  contract_version?: "codev-client-1";
  state: "absent" | "installed_unavailable" | "installed_ready" | "incompatible" | "degraded";
  installed?: boolean;
  usable?: boolean;
  version?: string | null;
  expected_version?: "1.0.0";
  contract_versions?: Array<string>;
  source?: "none" | "legacy_install_receipt";
  capabilities?: Array<Capability>;
  note: string;
  raw_paths_exposed?: false;
};

export type OperationReceipt = {
  contract_version?: "codev-receipt-1";
  operation_id: string;
  request_id: string;
  workspace_id?: string | null;
  status: "proposed" | "approval_required" | "approved" | "queued" | "running" | "completed" | "failed" | "cancelled" | "partial" | "blocked" | "conflict" | "verification_required";
  summary: string;
  base_revision?: number | null;
  resulting_revision?: number | null;
  files_inspected?: Array<string>;
  files_changed?: Array<string>;
  commands_run?: Array<Array<string>>;
  tests_run?: Array<string>;
  network_used?: boolean;
  outward_destination?: string | null;
  artifacts?: Array<ResultArtifact>;
  recovery_note?: string | null;
  verification?: "not_run" | "passed" | "failed" | "partial" | "required";
  audit_written?: boolean;
  warnings?: Array<string>;
  created_at: string;
};

export type PairingIntent = {
  contract_version?: "codev-pairing-1";
  intent_id: string;
  online_account_id: string;
  account_label: string;
  origin: "https://elysiaecobotics.com" | "https://www.elysiaecobotics.com";
  surface: "marketplace" | "forge";
  browser_session_id: string;
  browser_public_key: BrowserPublicKey;
  expires_at: string;
  status?: "pending" | "native_approved" | "paired" | "denied" | "expired" | "revoked";
};

export type PairingSession = {
  contract_version?: "codev-pairing-1";
  pairing_id: string;
  actor: Actor;
  browser_session_id: string;
  browser_public_key: BrowserPublicKey;
  native_public_key: BrowserPublicKey;
  expires_at: string;
  installation: Installation;
  workspace_grants?: Array<WorkspaceGrant>;
  note?: "Connected to local Codev. No workspace shared.";
};

export type ResultArtifact = {
  artifact_id: string;
  label: string;
  content_type: string;
  relative_path?: string | null;
};

export type WorkspaceDescriptor = {
  contract_version?: "codev-workspace-1";
  workspace_id: string;
  workspace_type: "local_repository" | "selected_local_files" | "marketplace_browser" | "forge_browser" | "remote_draft_snapshot";
  label: string;
  owner: Actor;
  base_revision: number;
  current_revision: number;
  base_hash: string;
  content_hash: string;
  files?: Array<WorkspaceFile>;
  allowed_operations?: Array<string>;
  denied_classes?: Array<string>;
  grant_epoch?: number;
  dirty?: boolean;
  validation_revision?: number | null;
  package_revision?: number | null;
};

export type WorkspaceFile = {
  path: string;
  content_hash?: string | null;
  size_bytes: number;
  availability: "text" | "binary" | "oversized" | "metadata_only" | "excluded" | "missing";
  text?: string | null;
  provenance: "local_file" | "intake" | "editor" | "codev_patch" | "remote_draft" | "recovery";
};

export type WorkspaceGrant = {
  grant_id: string;
  workspace_id: string;
  actor: Actor;
  epoch: number;
  scopes?: Array<"metadata" | "read" | "propose" | "apply" | "command">;
  files?: Array<string>;
  command_ids?: Array<string>;
  network_destinations?: Array<string>;
  expires_at: string;
  revoked?: boolean;
};
