-- Public release seed boundary.
--
-- Marketplace records must originate from the governed submission and review
-- workflow. Core/profile dependencies and planned integrations are not add-ons,
-- so this seed intentionally creates no public Marketplace records.
--
-- Test data belongs in isolated test fixtures, never in the hosted catalog.
