/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=scripts/config/codev-pages-types.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=CodevPagesBindings functions/codev-bindings.d.ts` (hash: ec1c4bcca4292413ae5fc88848f24483)
interface __BaseEnv_CodevPagesBindings {
	SUPABASE_URL: string;
	SUPABASE_PUBLISHABLE_KEY: string;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CodevPagesBindings {}
}
interface CodevPagesBindings extends __BaseEnv_CodevPagesBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SUPABASE_URL" | "SUPABASE_PUBLISHABLE_KEY">> {}
}
