export type AddonIssueLevel = "error" | "warning" | "info";
export type AddonIssue = {
  level: AddonIssueLevel;
  severity: AddonIssueLevel;
  code: string;
  message: string;
  path?: string;
  field_path?: string;
  suggestion?: string;
  fix_suggestion?: string;
};
export type AddonManifest = Record<string, unknown> & {
  schema_version?: string;
  addon_id?: string;
  name?: string;
  version?: string;
  permissions?: string[];
  runtime?: { kind?: string; requires_network?: boolean; requires_filesystem?: boolean };
  runtime_kind?: string;
  compatibility?: { elysia_min_version?: string; addon_api_version?: string };
  declared_domains?: string[];
  security?: { network_domains?: string[]; file_access?: string[] };
};
export type ArchiveInspectionResult = {
  status: "pass" | "warning" | "fail";
  risk_level: "low" | "medium" | "high" | "blocked";
  summary: string;
  errors: AddonIssue[];
  warnings: AddonIssue[];
  info: AddonIssue[];
  file_inventory: Array<{ path: string; kind: "file" | "directory"; size: number; scanned_as_text: boolean; sha256?: string }>;
  manifest_summary: null | { addon_id?: string; name?: string; version?: string; runtime_kind?: string; permissions: string[]; declared_domains: string[] };
  checksums_summary: null | { algorithm?: string; file_count: number; package_format_version?: string };
  sha256: string;
  archive_size: number;
  total_uncompressed_size: number;
};
export const supportedManifestSchema: string;
export const supportedAddonApi: string;
export const packageFormatVersion: string;
export const allowedRuntimeKinds: string[];
export const blockedPermissionKeys: string[];
export const permissionCatalog: Array<Record<string, unknown>>;
export const templateNames: string[];
export function isUnsafePackagePath(path: string): string | null;
export function parseManifestText(text: string): { manifest: AddonManifest | null; results: AddonIssue[] };
export function validateManifest(input: string | AddonManifest, options?: Record<string, unknown>): { manifest: AddonManifest | null; results: AddonIssue[] };
export function staticScanText(input?: { path?: string; fileName?: string; text?: string; manifestText?: string; extraText?: string; declaredDomains?: string[] }): AddonIssue[];
export function createDefaultManifest(addonId?: string, name?: string, overrides?: Record<string, unknown>): AddonManifest;
export function buildTemplateFiles(name?: string, template?: string): Array<{ path: string; contents: string }>;
export function sha256Bytes(bytes: Uint8Array | Buffer): string;
export function sha256Text(text: string): string;
export function buildPackageArchive(files: Array<{ path: string; contents: string | Uint8Array | Buffer }>, options?: Record<string, unknown>): Promise<{ buffer: Buffer; sha256: string; checksums: Record<string, string> }>;
export function inspectArchiveBuffer(buffer: Uint8Array | Buffer, options?: Record<string, unknown>): Promise<ArchiveInspectionResult>;
export function inspectArchiveFile(file: File | Uint8Array | Buffer, options?: Record<string, unknown>): Promise<ArchiveInspectionResult>;
