export type CommonsStewardshipOrganization = {
  id: string;
  name: string;
  category: string;
  officialUrl: string;
  shortDescription: string;
  whyListed: string;
  cautionNote: string;
  status: "independent organization";
  noPartnershipNotice: true;
};

export const commonsStewardshipOrganizations: CommonsStewardshipOrganization[] = [
  { id: "rainforest-trust", name: "Rainforest Trust", category: "Conservation and environmental justice", officialUrl: "https://www.rainforesttrust.org/", shortDescription: "Supports protection of threatened tropical habitats.", whyListed: "Relevant to biodiversity, habitat protection, and conservation stewardship.", cautionNote: "Review the organization's current programs and giving options directly before supporting.", status: "independent organization", noPartnershipNotice: true },
  { id: "amazon-conservation-team", name: "Amazon Conservation Team", category: "Conservation and environmental justice", officialUrl: "https://www.amazonteam.org/", shortDescription: "Works with Indigenous and local communities in Amazon conservation.", whyListed: "Aligned with forest stewardship, Indigenous knowledge respect, and ecological protection.", cautionNote: "Support should be direct through the organization's own site; no partnership is implied.", status: "independent organization", noPartnershipNotice: true },
  { id: "coral-reef-alliance", name: "Coral Reef Alliance", category: "Conservation and environmental justice", officialUrl: "https://coral.org/", shortDescription: "Focuses on coral reef conservation and resilient reef communities.", whyListed: "Relevant to reef stewardship, marine ecosystems, and climate resilience.", cautionNote: "Review current reef programs and regional work before supporting.", status: "independent organization", noPartnershipNotice: true },
  { id: "digdeep", name: "DIGDEEP Right to Water Project", category: "Conservation and environmental justice", officialUrl: "https://www.digdeep.org/", shortDescription: "Works on water access and water justice in the United States.", whyListed: "Connects water stewardship with dignity, access, and community infrastructure.", cautionNote: "Do not share personal billing or donation records here; keep proof redacted.", status: "independent organization", noPartnershipNotice: true },
  { id: "pure-earth", name: "Pure Earth", category: "Conservation and environmental justice", officialUrl: "https://www.pureearth.org/", shortDescription: "Works on pollution cleanup and toxic exposure reduction.", whyListed: "Relevant to soil, water, public health, and environmental justice stewardship.", cautionNote: "Review active projects and geographic focus directly on the official site.", status: "independent organization", noPartnershipNotice: true },
  { id: "sapa", name: "Sudanese American Physicians Association", category: "Conflict, refugees, and humanitarian relief", officialUrl: "https://sapa-usa.org/", shortDescription: "Medical and humanitarian support connected to Sudanese communities.", whyListed: "Relevant to crisis relief, health dignity, and humanitarian stewardship.", cautionNote: "Humanitarian contexts are sensitive; support directly and avoid sharing private beneficiary details.", status: "independent organization", noPartnershipNotice: true },
  { id: "pcrf", name: "Palestine Children's Relief Fund", category: "Conflict, refugees, and humanitarian relief", officialUrl: "https://www.pcrf.net/", shortDescription: "Medical and humanitarian relief for children and families.", whyListed: "Relevant to health, crisis support, and child welfare stewardship.", cautionNote: "Support directly through official channels; do not post personal donor records publicly.", status: "independent organization", noPartnershipNotice: true },
  { id: "razom", name: "Razom for Ukraine", category: "Conflict, refugees, and humanitarian relief", officialUrl: "https://www.razomforukraine.org/", shortDescription: "Humanitarian and civic support connected to Ukraine.", whyListed: "Relevant to crisis support, civic resilience, and humanitarian aid.", cautionNote: "Review current programs and verify donation routes on the official site.", status: "independent organization", noPartnershipNotice: true },
  { id: "halo-trust-usa", name: "The HALO Trust USA", category: "Conflict, refugees, and humanitarian relief", officialUrl: "https://www.halousa.org/", shortDescription: "Works on landmine and explosive hazard clearance.", whyListed: "Relevant to land safety, post-conflict recovery, and human/ecological restoration.", cautionNote: "Conflict-zone work can be complex; review current operations and reporting directly.", status: "independent organization", noPartnershipNotice: true },
  { id: "refugepoint", name: "RefugePoint", category: "Conflict, refugees, and humanitarian relief", officialUrl: "https://www.refugepoint.org/", shortDescription: "Supports refugee protection and self-reliance pathways.", whyListed: "Relevant to dignity, displacement, and humanitarian stewardship.", cautionNote: "Do not share sensitive refugee or personal data in public website contexts.", status: "independent organization", noPartnershipNotice: true },
  { id: "fistula-foundation", name: "Fistula Foundation", category: "Community health, family stability, and human dignity", officialUrl: "https://fistulafoundation.org/", shortDescription: "Supports treatment for obstetric fistula.", whyListed: "Relevant to health dignity and repair of preventable suffering.", cautionNote: "Health support is sensitive; keep any proof redacted and non-medical.", status: "independent organization", noPartnershipNotice: true },
  { id: "every-mother-counts", name: "Every Mother Counts", category: "Community health, family stability, and human dignity", officialUrl: "https://everymothercounts.org/", shortDescription: "Works to improve maternal health access.", whyListed: "Relevant to maternal health, family stability, and dignity.", cautionNote: "Review current programs directly; avoid sharing personal medical context here.", status: "independent organization", noPartnershipNotice: true },
  { id: "rainbow-railroad", name: "Rainbow Railroad", category: "Community health, family stability, and human dignity", officialUrl: "https://www.rainbowrailroad.org/", shortDescription: "Supports LGBTQI+ people facing persecution.", whyListed: "Relevant to safety, dignity, and humanitarian protection.", cautionNote: "Do not expose personal identity, location, or asylum-sensitive details in public drafts.", status: "independent organization", noPartnershipNotice: true },
  { id: "first-nations", name: "First Nations Development Institute", category: "Community health, family stability, and human dignity", officialUrl: "https://www.firstnations.org/", shortDescription: "Supports Native communities and economies.", whyListed: "Relevant to Indigenous stewardship, self-determination, and community resilience.", cautionNote: "Respect sovereignty, consent, and community context in any public discussion.", status: "independent organization", noPartnershipNotice: true },
  { id: "indspire", name: "Indspire", category: "Community health, family stability, and human dignity", officialUrl: "https://indspire.ca/", shortDescription: "Supports Indigenous education in Canada.", whyListed: "Relevant to education, dignity, and Indigenous futures.", cautionNote: "Review regional programs and eligibility directly on the official site.", status: "independent organization", noPartnershipNotice: true },
  { id: "camfed", name: "CAMFED USA Foundation", category: "Community health, family stability, and human dignity", officialUrl: "https://camfed.org/us/", shortDescription: "Supports girls' education and young women's leadership.", whyListed: "Relevant to education, community resilience, and public-benefit stewardship.", cautionNote: "Support directly; do not imply Elysia partnership or donation processing.", status: "independent organization", noPartnershipNotice: true },
  { id: "miraclefeet", name: "MiracleFeet", category: "Community health, family stability, and human dignity", officialUrl: "https://www.miraclefeet.org/", shortDescription: "Supports clubfoot treatment access.", whyListed: "Relevant to child health, mobility, and dignity.", cautionNote: "Health support proof should remain redacted and non-medical.", status: "independent organization", noPartnershipNotice: true },
  { id: "family-promise", name: "Family Promise", category: "Community health, family stability, and human dignity", officialUrl: "https://familypromise.org/", shortDescription: "Works to prevent and end family homelessness.", whyListed: "Relevant to housing stability, family dignity, and local community support.", cautionNote: "Avoid sharing private housing or family details in public contexts.", status: "independent organization", noPartnershipNotice: true },
  { id: "new-incentives", name: "New Incentives", category: "Community health, family stability, and human dignity", officialUrl: "https://www.newincentives.org/", shortDescription: "Supports childhood immunization through conditional cash transfers.", whyListed: "Relevant to public health, child welfare, and evidence-aware giving.", cautionNote: "Review current program details and evaluation information directly.", status: "independent organization", noPartnershipNotice: true },
  { id: "women-for-women", name: "Women for Women International", category: "Community health, family stability, and human dignity", officialUrl: "https://www.womenforwomen.org/", shortDescription: "Supports women survivors of war and conflict.", whyListed: "Relevant to dignity, livelihoods, and post-conflict recovery.", cautionNote: "Do not share survivor details or sensitive conflict context publicly.", status: "independent organization", noPartnershipNotice: true },
  { id: "nami", name: "National Alliance on Mental Illness / NAMI", category: "Mental health, crisis support, and family support", officialUrl: "https://www.nami.org/", shortDescription: "Mental health education, advocacy, and support resources.", whyListed: "Relevant to mental health literacy, family support, and crisis awareness.", cautionNote: "Do not share private mental health details or crisis information in public account pages.", status: "independent organization", noPartnershipNotice: true },
  { id: "wikimedia-foundation", name: "Wikimedia Foundation", category: "Knowledge commons", officialUrl: "https://wikimediafoundation.org/", shortDescription: "Supports Wikipedia and Wikimedia knowledge projects.", whyListed: "Relevant to public knowledge, open references, and the wider commons.", cautionNote: "Knowledge commons support does not imply training rights for all content; licenses vary by project/content.", status: "independent organization", noPartnershipNotice: true },
  { id: "creative-commons", name: "Creative Commons", category: "Knowledge commons", officialUrl: "https://creativecommons.org/", shortDescription: "Provides public licenses and open knowledge infrastructure.", whyListed: "Relevant to licensing literacy, attribution, reuse, and public knowledge stewardship.", cautionNote: "A Creative Commons license still has conditions; read the specific license before reuse.", status: "independent organization", noPartnershipNotice: true }
];
