import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import Ajv from "ajv";
import addFormats from "ajv-formats";
import standaloneCode from "ajv/dist/standalone/index.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const schemaPath = path.join(
  root,
  "src/pages/The-Developer-Forge/developerForgeManifest.schema.json",
);
const outputPath = path.join(
  root,
  "src/pages/The-Developer-Forge/developerForgeManifestValidator.generated.ts",
);
const schema = JSON.parse(await fs.readFile(schemaPath, "utf8"));

const ajv = new Ajv({
  allErrors: true,
  allowUnionTypes: true,
  strict: false,
  code: { source: true, esm: true },
});
addFormats(ajv);

const validate = ajv.compile(schema);
const standalone = standaloneCode(ajv, validate);
const generated = standalone.replace(
  'const formats0 = require("ajv-formats/dist/formats").fullFormats.uri;',
  'import formatsModule from "ajv-formats/dist/formats.js";const formats0 = formatsModule.fullFormats.uri;',
);
if (/\b(?:eval|new\s+Function|Function\s*\(|require\s*\()/.test(generated)) {
  throw new Error(
    "Generated Developer Forge validator contains runtime code evaluation or CommonJS loading.",
  );
}

const banner = [
  "// @ts-nocheck",
  "// Generated by scripts/generateDeveloperForgeManifestValidator.mjs.",
  "// Do not edit by hand. This standalone AJV validator is CSP-safe and must not compile schemas in the browser.",
  "",
].join("\n");
const output = `${banner}${generated}\n`;

if (process.argv.includes("--check")) {
  const current = await fs.readFile(outputPath, "utf8");
  if (current !== output)
    throw new Error(
      `${path.relative(root, outputPath)} is stale. Run npm run generate:developer-forge-validator.`,
    );
  console.log(
    `Verified ${path.relative(root, outputPath)} is current and contains no runtime evaluation.`,
  );
} else {
  await fs.writeFile(outputPath, output, "utf8");
  console.log(
    `Generated ${path.relative(root, outputPath)} without runtime evaluation.`,
  );
}
