/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.ui.sandbox.jsonc --env-file=/dev/null --include-runtime=false --strict-vars=false --env-interface=SandboxUiBindings services/sandbox-ui-worker/worker-configuration.d.ts` (hash: 7fb1c6cbf2ba44dcc0564f2cfcfa9dab)
interface __BaseEnv_SandboxUiBindings {
	ASSETS: Fetcher;
	SANDBOX_UI_ORIGIN: string;
	SUPABASE_URL: string;
	SANDBOX_ACCESS_TEAM_DOMAIN: string;
	SANDBOX_ACCESS_AUDIENCE: string;
	BILLING_SERVICE: Fetcher /* elysia-first-party-billing-sandbox */;
	IDENTITY_SERVICE: Fetcher /* elysia-shared-identity-sandbox */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_SandboxUiBindings {}
}
interface SandboxUiBindings extends __BaseEnv_SandboxUiBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SANDBOX_UI_ORIGIN" | "SUPABASE_URL" | "SANDBOX_ACCESS_TEAM_DOMAIN" | "SANDBOX_ACCESS_AUDIENCE">> {}
}
