import RefundPolicyGuide from "../../shared/economics/RefundPolicyGuide";
import JobPostFeeWorkspace from "../../shared/economics/JobPostFeeWorkspace";
import { canVisitStaffRoute, useAccountDoorways } from "../../shared/navigation/useAccountDoorways";
import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import PageHero from "../../shared/components/PageHero";
import { preparationSections, type PreparationOverview, type PreparationSection } from "../../shared/economics/preProviderContracts.ts";
import { usePreparation } from "../../shared/economics/usePreparation.ts";
import { PreparationBlockers, PreparationForm, PreparationReason, PreparationRecords, PreparationStatus, PreparationUnavailable, ProviderHandoffNotice, preparationMoney } from "../../shared/economics/PreparationComponents";
import EconomicOperationsNavigation from "./EconomicOperationsNavigation";
const value = (data: FormData, name: string) => String(data.get(name) ?? "");
type Work = ReturnType<typeof usePreparation>;
const existingTools: Partial<Record<PreparationSection, [string, string][]>> = {
  support: [["/commons-circle/support-billing", "Personal Support & Billing"], ["/admin/economic-operations", "Existing support and subscription queues"]],
  refunds: [["/admin/economic-operations#refund-hold-title", "Existing governed refund review"], ["/admin/economic-operations", "Disputes and reconciliation"]],
  organizations: [["/admin/economic-operations", "Organization records, memberships, services and contract review"]],
  sponsorship: [["/admin/economic-operations", "Sponsorship agreements, ethics review and allocations"]],
  "job-fees": [["/admin/economic-operations", "Job Post fee assessment and assistance reconciliation"], ["/admin/review/commune", "Independent content review"]],
  "hosted-allowance": [["/commons-circle/settings/hosted-execution", "Hosted allowance account"], ["/admin/economic-operations", "Existing operational credit adjustments"]],
  audit: [["/admin/economic-operations", "Existing economic audit and accounting export"], ["/admin/audit", "Governance audit remains separate"]]
};
function SellerReviews({ work, state }: { work: Work; state: PreparationOverview }) {
  return <section className="section-card"><h2>Internal seller applications</h2><p>Economic review cannot verify a publisher, approve an add-on or grant community authority. A creator cannot approve their own application.</p>{!state.sellers.length && <p>No seller applications are in this capability-filtered view.</p>}{state.sellers.map(seller => <article className="economic-summary-card" key={seller.sellerId}><h3>{seller.displayName}</h3><p>{seller.intent} · {seller.status.replace(/_/g, " ")} · revision {seller.revision}</p><PreparationBlockers blockers={seller.blockers} />{["submitted", "approved", "suspended"].includes(seller.status) && <PreparationForm title="Record internal review" busy={work.busy || !state.lanes.sellers} label="Record seller decision" submit={data => work.run({ action: "seller_review", sellerId: seller.sellerId, expectedRevision: seller.revision, decision: value(data, "decision") as "approved" | "changes_requested" | "rejected" | "suspended", reason: value(data, "reason") })}><label><span>Decision</span><select name="decision">{seller.status === "submitted" ? <><option value="changes_requested">Request changes</option><option value="approved">Approve internal preparation</option><option value="rejected">Reject preparation</option></> : seller.status === "approved" ? <option value="suspended">Suspend internal readiness</option> : <option value="changes_requested">Return for corrections</option>}</select></label><PreparationReason /></PreparationForm>}</article>)}</section>;
}
function OfferReviews({ work, state }: { work: Work; state: PreparationOverview }) {
  return <section className="section-card"><h2>Offering preparation</h2><p>Free offerings carry no fee. Commercial drafts retain their own selected proposal and license version; none is a live purchasable offer.</p>{state.offers.map(offer => <article className="economic-summary-card" key={offer.offerId}><h3>{offer.kind === "free" ? "Free offering" : "Commercial draft"} · {preparationMoney(offer.amountMinor, offer.currency)}</h3><p>{offer.status.replace(/_/g, " ")} · {offer.licenseKey} {offer.licenseVersion} · revision {offer.revision}</p><PreparationBlockers blockers={offer.blockers} />{offer.status !== "retired" && <PreparationForm title="Review offering preparation" busy={work.busy || !state.lanes.sellers} label="Record offering review" submit={data => work.run({ action: "offer_review", offerId: offer.offerId, expectedRevision: offer.revision, decision: value(data, "decision") as "prepared" | "changes_requested" | "retired", reason: value(data, "reason") })}><label><span>Decision</span><select name="decision"><option value="changes_requested">Request changes</option><option value="prepared">Mark internal preparation complete</option><option value="retired">Retire draft</option></select></label><PreparationReason /></PreparationForm>}</article>)}{!state.offers.length && <p>No offering drafts are in this bounded view.</p>}</section>;
}
function Proposals({ work, state }: { work: Work; state: PreparationOverview }) {
  const [kind, setKind] = useState<"marketplace_fee_bps" | "proof_retention_days">("marketplace_fee_bps");
  return <section className="section-card"><h2>Adopted owner policy · provider approval pending</h2><p>Adopted September 10, 2026: 5% on paid third-party Marketplace sales, 0% on free add-ons, no buyer convenience fee; $10 commercial Job Posts; 30-day stewardship-proof retention after final review or appeal closure. Provider actions and fee collection remain disabled. Historical proposals below are retained without rewriting their original status.</p><div className="economic-capability-grid">{state.proposals.map(proposal => <article className="economic-summary-card" key={proposal.proposalId}><PreparationStatus status="BLOCKED" /><p><strong>{proposal.kind === "marketplace_fee_bps" ? `${proposal.value / 100}% Marketplace fee` : `${proposal.value} days proof retention`}</strong></p><p>Historical proposal record · current policy stated above</p><small>{new Date(proposal.createdAt).toLocaleString()}</small></article>)}</div>{state.capabilities.includes("economic_feature_flags_manage") && <PreparationForm title="Record another proposal" busy={work.busy} label="Save proposal without adoption" submit={data => work.run({ action: "policy_propose", kind, value: Number(data.get("value")), reason: value(data, "reason") })}><label><span>Policy proposal</span><select value={kind} onChange={event => setKind(event.target.value as typeof kind)}><option value="marketplace_fee_bps">Marketplace fee in basis points</option><option value="proof_retention_days">Optional proof retention in days</option></select></label><label><span>{kind === "marketplace_fee_bps" ? "Basis points (500 = 5%)" : "Days after approved closure conditions"}</span><input key={kind} type="number" name="value" defaultValue={kind === "marketplace_fee_bps" ? 500 : 30} min={kind === "marketplace_fee_bps" ? 0 : 1} max={kind === "marketplace_fee_bps" ? 5000 : 365} step={1} required /></label><PreparationReason /></PreparationForm>}</section>;
}
function Settlements({ work, state }: { work: Work; state: PreparationOverview }) {
  return <>
    <PreparationForm title="Reconcile a Marketplace order" busy={work.busy || !state.lanes.settlements} label="Prepare current reconciliation snapshot" submit={data => { const orderId = value(data, "orderId"); return work.run({ action: "settlement_refresh", orderId, expectedRevision: state.settlements.find(item => item.orderId === orderId)?.revision ?? 0, reason: value(data, "reason") }); }}><label><span>Existing internal Marketplace order UUID</span><input name="orderId" required autoComplete="off" maxLength={36} /></label><PreparationReason /><p>The server reads the existing contract, payment, commission, refund and dispute records. No payment evidence or provider identifiers can be supplied in this form.</p></PreparationForm>
    <section className="section-card"><h2>Seller obligations and handoff preparation</h2><p>A purchase is distinct from creator proceeds, provider balance availability, a transfer and a completed bank payout. Unknown processor fees remain unknown.</p>{state.settlements.map(item => <article className="economic-summary-card" key={item.orderId}><PreparationStatus status="BLOCKED" /><h3>{item.status.replace(/_/g, " ")}</h3><dl className="mini-facts"><div><dt>Contract price</dt><dd>{preparationMoney(item.grossMinor, item.currency)}</dd></div><div><dt>Original platform fee</dt><dd>{preparationMoney(item.platformFeeMinor, item.currency)}</dd></div><div><dt>Original creator share before processor cost</dt><dd>{preparationMoney(item.creatorShareMinor, item.currency)}</dd></div><div><dt>Recorded creator ledger obligation</dt><dd>{preparationMoney(item.creatorPayableMinor, item.currency)}</dd></div><div><dt>Processor fee</dt><dd>{preparationMoney(item.processorFeeMinor, item.currency)}</dd></div><div><dt>Refunded</dt><dd>{preparationMoney(item.refundedMinor, item.currency)}</dd></div><div><dt>Dispute exposure</dt><dd>{preparationMoney(item.disputeExposureMinor, item.currency)}</dd></div><div><dt>Completed creator payout</dt><dd>Not verified</dd></div></dl><PreparationBlockers blockers={item.blockers} /><details><summary>Reconciliation reference</summary><p>Order <code>{item.orderId}</code> · revision {item.revision}</p><p>Evidence digest <code>{item.evidenceSha256}</code></p></details>{item.status !== "canceled" && <PreparationForm title="Review this snapshot" busy={work.busy || !state.lanes.settlements} label="Record preparation decision" submit={data => work.run({ action: "settlement_review", orderId: item.orderId, expectedRevision: item.revision, evidenceSha256: item.evidenceSha256, decision: value(data, "decision") as "hold" | "prepare_handoff" | "cancel", reason: value(data, "reason") })}><label><span>Decision</span><select name="decision"><option value="hold">Hold for review</option><option value="prepare_handoff">Prepare blocked provider handoff</option><option value="cancel">Cancel this preparation</option></select></label><PreparationReason /><p>Stale evidence, unresolved refunds/disputes and incomplete reconciliation prevent handoff preparation. No decision performs a payout.</p></PreparationForm>}</article>)}{!state.settlements.length && <p>No settlement preparations are in this bounded view.</p>}</section>
  </>;
}
function Waivers({ work, state }: { work: Work; state: PreparationOverview }) {
  return <><section className="section-card"><h2>EcoSyneva-owned amounts only</h2><p>A waiver can cover EcoSyneva's own platform fee, Job Post fee or first-party organization-service charge. It cannot reduce a creator's price/share, processor fee or taxes. Partial waivers reduce only the owned fee; full waivers cover it entirely. Recorded amounts track foregone revenue without creating an artificial cash budget. Actual cash/compute subsidies require separate bounded assistance. Refunds, promotions, assistance and sponsorship remain separate governed workflows.</p></section>
    <PreparationForm title="Approve an owned-fee waiver preparation" busy={work.busy || !state.lanes.waivers} label="Approve owned-fee preparation" submit={data => work.run({ action: "waiver_approve", orderId: value(data, "orderId"), component: value(data, "component") as "ecosyneva_platform_fee" | "ecosyneva_job_fee" | "ecosyneva_service_fee", amountMinor: Number(data.get("amountMinor")), reason: value(data, "reason"), confirmation: value(data, "confirmation") as "WAIVE ECOSYNEVA OWNED AMOUNT ONLY" })}><label><span>Existing uncommitted internal order UUID</span><input name="orderId" autoComplete="off" required maxLength={36} /></label><label><span>EcoSyneva-owned component</span><select name="component"><option value="ecosyneva_platform_fee">EcoSyneva Marketplace platform fee only</option><option value="ecosyneva_job_fee">EcoSyneva Job Post fee</option><option value="ecosyneva_service_fee">EcoSyneva organization-service fee</option></select></label><label><span>Waived amount in the order's minor currency units</span><input type="number" name="amountMinor" min={1} max={100_000_000_000} step={1} required /></label><PreparationReason /><label><span>Type WAIVE ECOSYNEVA OWNED AMOUNT ONLY</span><input name="confirmation" autoComplete="off" required /></label><p>Ownership, original amount and cumulative waivers are checked from the existing order/contract. The original price remains immutable. The old checkout adapter is blocked from ignoring an approved waiver.</p></PreparationForm>
    <section className="section-card"><h2>Audited waiver preparations</h2>{state.waivers.map(item => <article className="economic-summary-card" key={item.waiverId}><strong>{preparationMoney(item.amountMinor, item.currency)} · {item.component.replace(/_/g, " ")}</strong><p>{item.status.replace(/_/g, " ")} · revision {item.revision}</p><p>Reason: {item.reason}</p><p>Actor <code>{item.actorId}</code> · {new Date(item.createdAt).toLocaleString()}</p><p>Charge <code>{item.orderId}</code></p>{item.status === "approved_preparation" && <PreparationForm title="Revoke this preparation" busy={work.busy || !state.lanes.waivers} label="Record waiver revocation" submit={data => work.run({ action: "waiver_revoke", waiverId: item.waiverId, expectedRevision: item.revision, reason: value(data, "reason") })}><PreparationReason /></PreparationForm>}</article>)}{!state.waivers.length && <p>No waiver preparations are in this capability-filtered view.</p>}</section></>;
}
function SupportReviews({ work, state }: { work: Work; state: PreparationOverview }) {
  return <section className="section-card"><h2>Support follow-up review</h2><p>These cases prepare cancellation, refund or acknowledgment follow-up. Subscription and payment truth remain in their separate records.</p>{state.subscriptions.map(item => <article className="economic-summary-card" key={item.subscriptionId}><strong>Recurring support · {item.status.replace(/_/g, " ")}</strong><p>{item.cancelAtPeriodEnd ? "Cancellation scheduled in the verified record" : "No scheduled cancellation in this record"}</p><code>{item.subscriptionId}</code></article>)}{state.supportCases.map(item => <article className="economic-summary-card" key={item.caseId}><h3>{item.kind.replace(/_/g, " ")}</h3><p>{item.status.replace(/_/g, " ")} · {item.reason}</p>{item.status !== "declined" && state.capabilities.includes("economic_refunds_manage") && <PreparationForm title="Review support request" busy={work.busy || !state.lanes.support} label="Record follow-up review" submit={data => work.run({ action: "support_review", caseId: item.caseId, expectedRevision: item.revision, decision: value(data, "decision") as "reviewing" | "awaiting_provider" | "declined", reason: value(data, "reason") })}><label><span>Decision</span><select name="decision">{item.status !== "reviewing" && <option value="reviewing">Reviewing</option>}{item.status === "reviewing" && <option value="awaiting_provider">Internal review complete; awaiting provider</option>}<option value="declined">Decline request with reason</option></select></label><PreparationReason /></PreparationForm>}</article>)}{!state.supportCases.length && <p>No support follow-up cases are in this bounded view.</p>}</section>;
}
function LaneContext({ section }: { section: PreparationSection }) {
  const copy: Partial<Record<PreparationSection, string>> = {
    organizations: "Existing organization identities, memberships, contracts, service entitlements and review tools remain available in the original operations console. EcoSyneva-owned service-fee waiver preparation is separate from assistance and provider collection.",
    sponsorship: "Ethical review, countersigned agreements, allocations, recognition opt-in and independent publication gates remain intact. Sponsorship does not buy governance, endorsement or control of recipients.",
    "job-fees": "Commercial Job Post fee assessments and governed assistance remain separate from content approval. Only EcoSyneva's owned charge can be waived; no payment or waiver publishes a post.",
    "hosted-allowance": "Shared infrastructure remains available under payment-independent eligibility and operating limits. The dormant Support-to-sandbox-credit trigger is quarantined by the prepared migration. Existing balances, correction history and safety limits remain intact.",
    legal: "Published legal text and historical acceptances are immutable. New fee or retention proposals do not change active legal pointers. Approval of internal seller preparation does not adopt commercial policies or grant provider consent."
  };
  return copy[section] ? <section className="section-card"><PreparationStatus status="BLOCKED" /><h2>Preserved operational boundaries</h2><p>{copy[section]}</p>{section === "legal" && <div className="button-row"><Link to="/legal/marketplace-commerce-terms">Current Marketplace terms</Link><Link to="/legal/support-and-billing-terms">Support & Billing Terms</Link><Link to="/legal/donation-recognition-terms">Independent stewardship terms</Link></div>}</section> : null;
}
export default function EconomicOperationsSectionPage() {
  const { section: requested } = useParams();
  const access = useAccountDoorways();
  const entry = preparationSections.find(([key]) => key === requested);
  const work = usePreparation("operator");
  if (!entry) return <section className="section-card"><h1>Economic section not found</h1><Link to="/admin/economic-operations">Return to Economic Operations</Link></section>;
  const [section, title] = entry; const state = work.state;
  const can = (capability: string) => Boolean(state?.capabilities.includes(capability));
  return <div className="page-stack economic-operations-page preparation-workspace"><PageHero eyebrow="Economic Operations" title={title} brandMark="standard"><p>Private internal preparation, explicit authority and separate financial records. Existing admin and economic routes remain available.</p></PageHero><EconomicOperationsNavigation />
    {work.loading && <p role="status">Checking economic preparation authority…</p>}{work.error && <p role="alert" className="validation validation--bad">{work.error}</p>}<p role="status" aria-live="polite">{work.message}</p>
    {!state && !work.loading && <PreparationUnavailable signedIn={work.signedIn} published={work.published} />}
    <LaneContext section={section} />
    {section === "refunds" && <RefundPolicyGuide />}
    {section === "job-fees" && canVisitStaffRoute("/admin/economic-operations/job-fees", access) && <JobPostFeeWorkspace operator />}
    {state && <>
      <section className="section-card"><PreparationStatus status="TEST" /><h2>Internal preparation · provider actions disabled</h2><p>Financial records here belong to the existing test-only economic kernel. READY means internal prerequisites only. This interface cannot authorize live billing, Connect, payouts, receipt delivery or bank access.</p><button type="button" onClick={() => void work.refresh()} disabled={work.busy}>Refresh private preparation</button>{state.truncated && <p className="boundary-note">This bounded view may omit older records. A missing row is not proof that it does not exist.</p>}</section>
      {section === "readiness" && <section className="section-card"><h2>Preparation lanes</h2><div className="economic-capability-grid">{Object.entries(state.lanes).map(([lane, enabled]) => <article className="economic-summary-card" key={lane}><h3>{lane}</h3><PreparationStatus status={enabled ? "TEST" : "DISABLED"} /><p>{enabled ? "Internal preparation enabled in this test view." : "Internal preparation gate is disabled."}</p></article>)}</div><p>Support is optional. Creator obligations, taxes, refunds and disputes are separate from EcoSyneva operating funds. Continuity Reserve and compensation categories are internal planning concepts; no funded balance or allocation is claimed.</p></section>}
      {["sellers", "onboarding"].includes(section) && can("marketplace_payout_manage") && <SellerReviews work={work} state={state} />}
      {section === "offers" && can("marketplace_payout_manage") && <OfferReviews work={work} state={state} />}
      {["offers", "legal", "readiness"].includes(section) && <Proposals work={work} state={state} />}
      {section === "settlement" && can("marketplace_payout_manage") && <Settlements work={work} state={state} />}
      {section === "waivers" && can("economic_assistance_manage") && <Waivers work={work} state={state} />}
      {["support", "refunds"].includes(section) && (can("economic_refunds_manage") || can("recurring_support_manage")) && <SupportReviews work={work} state={state} />}
      {["receipts", "support", "refunds"].includes(section) && <PreparationRecords records={state.records} />}
      {section === "audit" && can("economic_audit_view") && <section className="section-card"><h2>Immutable preparation audit</h2>{state.audit.map(item => <article className="economic-summary-card" key={item.eventId}><strong>{item.action.replace(/_/g, " ")}</strong><p>{item.reason ?? "Structured preparation action"}</p><p>Actor <code>{item.actorId}</code> · {new Date(item.createdAt).toLocaleString()}</p><p>Target <code>{item.targetId}</code></p></article>)}{!state.audit.length && <p>No events are in this bounded page.</p>}</section>}
    </>}
    {["provider", "onboarding", "readiness"].includes(section) && <ProviderHandoffNotice />}
    {section === "provider" && <section className="section-card"><h2>Qualification still required</h2><ul><li>Owner authorization and provider approval for each financial lane.</li><li>Adopted charge model, seller responsibilities, fees, taxes and refund/dispute treatment.</li><li>Qualified account-scoped events, cancellation, receipt delivery and settlement evidence.</li><li>Separate audited release, migrations and exact activation flags.</li></ul><p>No credential entry, provider mutation or activation toggle exists on this page. The existing Stripe adapter is preserved; no additional provider is presented as integrated.</p></section>}
    {(existingTools[section] ?? []).some(([route]) => canVisitStaffRoute(route, access)) && <section className="section-card"><h2>Existing working tools</h2><div className="button-row">{existingTools[section]!.filter(([route]) => canVisitStaffRoute(route, access)).map(([route, label]) => <Link className="button-link" key={route} to={route}>{label}</Link>)}</div><p>These tools retain their existing routes, behavior, capability checks and financial gates.</p></section>}
  </div>;
}
